name = "Perpendicular 2.0"
author = "The Parallel Team"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbaf3d5dc2ccbc630565c77795d0df1f92a08829ac04d2c57ab72be564152d10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[options]
acceptable-game-versions = []
