name = "Perpendicular 2.0"
author = "The Parallel Team"
version = "Alpha 1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebcfcf61cfa844fee99115864d211d2110ef5148d792368d8a525badccaba082"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = []
